-- Generated by scripts/make-seed.mjs from data/mock-data.json. Do not edit by hand.
-- Catalog and settings only. Rates marked ratesToConfirm are placeholders until the owner confirms them.

insert into public.settings (key, value) values
  ('meta', '{"description":"V6M Resort and Events Place: V6M Desk","timezone":"Asia/Manila","currency":"PHP","rules":["A unit holds one booking per night; exclusive events that are reserved, paid or done close the resort for the day.","Regular bookings: per-head entrance for a session (day tour 8 AM–4 PM, night tour 2 PM–10 PM, overnight 3 PM–12 NN, overnight tour 6 PM–6 AM), plus cottages or rooms. Each session caps at 120 guests.","Night tour and 3 PM overnight entrance rates are placeholders until the owner confirms them.","Exclusive rental packages (from the brochure) close the resort to other bookings for their whole time window, and need that window to be free. Up to 120 guests.","Rooms (3 PM–12 NN) and cottages (6 PM–6 AM) add per-head entrance for their session.","A booking stays on hold until at least 50% of the total is paid; checked-out bookings have zero balance.","Downpayment: 50% of the total for every booking, rounded up to the peso. Guests on a booking link pay it by GCash QR.","Booking links are single use: a staff member sends one, the guest fills it in, and the booking lands on the calendar.","Rates come from public listings and the V6M brochure; promo PR-BTS and all event packages are invented for testing.","V6M Desk signs in with an email and password. Demo passwords sit in this file in plain text because it is a mock; a real build would never store them this way.","New accounts are invite only: the owner creates the account, the invite code is used once, and the person sets their own password.","Owners and managers can give a manual discount (amount or percent). Managers must write a note saying why; owners may skip it. The 50% downpayment follows the discounted total."],"counts":{"staff":2,"units":6,"guests":53,"bookings":42,"payments":36,"events":1,"inquiries":40,"activityLog":91}}'::jsonb),
  ('amenities', '["3 pools (adult and kiddie)","7 kubo cottages","7 air-conditioned villas","Free Wi-Fi","Grilling area","Ample parking"]'::jsonb)
on conflict (key) do update set
  value = excluded.value;

insert into public.pool_sessions (id, label, start, "end", adult, kid, capacity, photo, sort, rates_to_confirm) values
  ('daytour', 'Day tour', '08:00', '16:00', 150, 100, 120, 'pool.jpg', 0, default),
  ('nighttour', 'Night tour', '14:00', '22:00', 180, 130, 120, 'garden.jpg', 1, true),
  ('overnightstay', 'Overnight', '15:00', '12:00', 200, 150, 120, 'villas.jpg', 2, true),
  ('overnight', 'Overnight tour', '18:00', '06:00', 200, 150, 120, 'garden.jpg', 3, default)
on conflict (id) do update set
  label = excluded.label,
  start = excluded.start,
  "end" = excluded."end",
  adult = excluded.adult,
  kid = excluded.kid,
  capacity = excluded.capacity,
  photo = excluded.photo,
  sort = excluded.sort,
  rates_to_confirm = excluded.rates_to_confirm;

insert into public.exclusive_packages (id, session, "use", name, includes, start, "end", price, max_guests, photo, sort) values
  ('EX-DAY-FULL', 'day', 'full', 'Full resort use', 'All rooms + all amenities', '08:00', '16:00', 40000, 120, 'pkg-full.jpg', 0),
  ('EX-DAY-PARTIAL', 'day', 'partial', 'Partial room use', '3 rooms + all amenities', '08:00', '16:00', 35000, 120, 'pkg-partial.jpg', 1),
  ('EX-DAY-COTTAGES', 'day', 'cottages', 'Cottages only', 'All kubo cottages + all amenities', '08:00', '16:00', 30000, 120, 'pkg-cottages.jpg', 2),
  ('EX-NIGHT-FULL', 'overnight', 'full', 'Full resort use', 'All rooms + all amenities', '15:00', '12:00', 50000, 120, 'pkg-full.jpg', 3),
  ('EX-NIGHT-PARTIAL', 'overnight', 'partial', 'Partial room use', '3 rooms + all amenities', '15:00', '12:00', 45000, 120, 'pkg-partial.jpg', 4),
  ('EX-NIGHT-COTTAGES', 'overnight', 'cottages', 'Cottages only', 'All kubo cottages + all amenities', '18:00', '06:00', 40000, 120, 'pkg-cottages.jpg', 5)
on conflict (id) do update set
  session = excluded.session,
  "use" = excluded."use",
  name = excluded.name,
  includes = excluded.includes,
  start = excluded.start,
  "end" = excluded."end",
  price = excluded.price,
  max_guests = excluded.max_guests,
  photo = excluded.photo,
  sort = excluded.sort;

insert into public.units (id, name, kind, capacity_min, capacity_max, price, check_in, check_out, session, adds_entrance, inclusions, photo, sort) values
  ('suite', 'Suite room', 'room', 1, 6, 2500, '15:00', '12:00', 'overnightstay', true, '["Air-conditioning","Smart TV","Hot and cold shower","Wi-Fi"]'::jsonb, 'room-orange.jpg', 0),
  ('deluxe', 'Deluxe room', 'room', 1, 2, 2200, '15:00', '12:00', 'overnightstay', true, '["Air-conditioning","Smart TV","Hot and cold shower","Wi-Fi"]'::jsonb, 'room-bunk.jpg', 1),
  ('cottageA', 'Cottage A', 'cottage', 10, 15, 2000, '18:00', '06:00', 'overnight', true, '["Poolside table and benches"]'::jsonb, 'kubo.jpg', 2),
  ('cottageB', 'Cottage B', 'cottage', 8, 10, 1500, '18:00', '06:00', 'overnight', true, '["Poolside table and benches"]'::jsonb, 'kubo.jpg', 3),
  ('cottageC', 'Cottage C', 'cottage', 4, 6, 1000, '18:00', '06:00', 'overnight', true, '["Poolside table"]'::jsonb, 'kubo.jpg', 4)
on conflict (id) do update set
  name = excluded.name,
  kind = excluded.kind,
  capacity_min = excluded.capacity_min,
  capacity_max = excluded.capacity_max,
  price = excluded.price,
  check_in = excluded.check_in,
  check_out = excluded.check_out,
  session = excluded.session,
  adds_entrance = excluded.adds_entrance,
  inclusions = excluded.inclusions,
  photo = excluded.photo,
  sort = excluded.sort;

insert into public.promos (id, name, percent, valid_from, valid_to, weekdays, min_pax, applies_to, active, source) values
  ('PR-RAINY', 'Rainy season promo', 15, '2026-07-01', '2026-08-31', '[1,2,3,4]'::jsonb, 0, '["daytour","overnight","suite","deluxe","cottageA","cottageB","cottageC"]'::jsonb, false, 'From the resort''s Instagram, Jul–Aug'),
  ('PR-BTS', 'Back-to-school weekday barkada', 10, '2026-09-01', '2026-09-30', '[1,2,3,4]'::jsonb, 10, '["daytour","overnight","cottageA","cottageB"]'::jsonb, true, 'Mock promo for testing the rate engine')
on conflict (id) do update set
  name = excluded.name,
  percent = excluded.percent,
  valid_from = excluded.valid_from,
  valid_to = excluded.valid_to,
  weekdays = excluded.weekdays,
  min_pax = excluded.min_pax,
  applies_to = excluded.applies_to,
  active = excluded.active,
  source = excluded.source;

insert into public.event_packages (id, name, price, max_guests, exclusive, hours, inclusions, sort) values
  ('PKG-DEBUT', 'Debut package', 45000, 80, true, '14:00-06:00', '["Exclusive use of pool and garden","Suite room for the celebrant","Sound system hookup","Overnight for up to 20 family members"]'::jsonb, 0),
  ('PKG-WEDDING', 'Intimate wedding', 60000, 100, true, '10:00-22:00', '["Exclusive use of venue","Suite and Deluxe rooms","Garden ceremony area","Grilling station"]'::jsonb, 1),
  ('PKG-BDAY', 'Birthday pool party', 25000, 50, true, '10:00-22:00', '["Exclusive use of pool","Cottage A and B","Grilling station"]'::jsonb, 2),
  ('PKG-PRENUP', 'Prenup photoshoot', 8000, 10, false, '06:00-09:00', '["3-hour morning access to pool and garden","Suite room for styling"]'::jsonb, 3)
on conflict (id) do update set
  name = excluded.name,
  price = excluded.price,
  max_guests = excluded.max_guests,
  exclusive = excluded.exclusive,
  hours = excluded.hours,
  inclusions = excluded.inclusions,
  sort = excluded.sort;

insert into public.saved_replies (id, title, body, sort) values
  ('SR-RATES', 'Rates', 'Hola! Thanks for reaching V6M Resort.

Day tour (8 AM–4 PM): ₱150 adults, ₱100 kids
Overnight tour (6 PM–6 AM): ₱200 adults, ₱150 kids
Cottages: A ₱2,000 · B ₱1,500 · C ₱1,000
Rooms (3 PM–12 NN): Suite ₱2,500 · Deluxe ₱2,200, plus entrance

Want the place to yourselves? Exclusive rental, up to 120 guests:
Day tour: Full resort ₱40,000 · Partial room use ₱35,000 · Cottages only ₱30,000
Overnight: Full resort ₱50,000 · Partial room use ₱45,000 (3 PM–12 NN) · Cottages only ₱40,000 (6 PM–6 AM)

So, when''s your next vacay?', 0),
  ('SR-PETS', 'Pets', 'Yes, we''re pet-friendly! Dogs and cats are welcome as long as they wear diapers or stay in cages.', 1),
  ('SR-DIRECTIONS', 'Directions', 'We''re at Purok 3, Brgy. Munting Pulo, Lipa City, Batangas, about 10 minutes from SM Lipa. Message us when you''re near and we''ll guide you.', 2),
  ('SR-DEPOSIT', 'Down payment', 'To lock in your date, send a 50% down payment via GCash or bank transfer and share the screenshot here. We''ll confirm right away.', 3),
  ('SR-EVENTS', 'Events', 'Congrats in advance! We''d love to host. Share your date, headcount and type of event, and we''ll send packages and schedule an ocular visit.', 4),
  ('SR-EXCLUSIVE', 'Exclusive rental', '100% exclusive. No sharing, no strangers. The whole resort is yours: 3 pools, 7 kubo cottages, 7 air-conditioned villas, free Wi-Fi, a grilling area and ample parking, for up to 120 guests.

Day tour (8 AM–4 PM): Full resort ₱40,000 · Partial room use (3 rooms) ₱35,000 · Cottages only ₱30,000
Overnight: Full resort ₱50,000 · Partial room use ₱45,000 (3 PM–12 NN) · Cottages only ₱40,000 (6 PM–6 AM)

A 50% downpayment locks your date.', 5)
on conflict (id) do update set
  title = excluded.title,
  body = excluded.body,
  sort = excluded.sort;
