// Writes supabase/seed.sql: the resort's catalog (rates, rooms, packages,
// promos, saved replies) and settings, taken from data/mock-data.json.
// No sample guests, bookings or payments: production starts empty.
//
// Re-run after changing rates in the mock data: `npm run seed:make`.
// Every insert is an upsert, so running the seed again updates the rates.

import { readFileSync, writeFileSync } from 'node:fs';

const data = JSON.parse(readFileSync('data/mock-data.json', 'utf8'));

const snake = (key) => key.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`);
const quote = (text) => `'${String(text).replaceAll("'", "''")}'`;
const RESERVED = new Set(['end', 'from', 'use']);
const column = (name) => (RESERVED.has(name) ? `"${name}"` : name);

function literal(value) {
  if (value === null || value === undefined) return 'null';
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (typeof value === 'object') return `${quote(JSON.stringify(value))}::jsonb`;
  return quote(value);
}

function upsert(table, rows, { key = 'id', sorted = false } = {}) {
  if (!rows.length) return '';
  const records = rows.map((row, index) => {
    const record = Object.fromEntries(Object.entries(row).map(([field, value]) => [snake(field), value]));
    return sorted ? { ...record, sort: index } : record;
  });
  const columns = [...new Set(records.flatMap((record) => Object.keys(record)))];
  // A field a row leaves out takes the column's default, not null.
  const values = records.map((record) => `  (${columns.map((name) => (name in record ? literal(record[name]) : 'default')).join(', ')})`);
  const updates = columns.filter((name) => name !== key).map((name) => `${column(name)} = excluded.${column(name)}`);
  return `insert into public.${table} (${columns.map(column).join(', ')}) values\n${values.join(',\n')}\non conflict (${key}) do update set\n  ${updates.join(',\n  ')};\n`;
}

// The demo's frozen date and seed mean nothing in production.
const { asOf: _asOf, period: _period, seed: _seed, ...meta } = data.meta;
meta.description = 'V6M Resort and Events Place: V6M Desk';

const sql = [
  '-- Generated by scripts/make-seed.mjs from data/mock-data.json. Do not edit by hand.',
  '-- Catalog and settings only. Rates marked ratesToConfirm are placeholders until the owner confirms them.',
  '',
  upsert('settings', [
    { key: 'meta', value: meta },
    { key: 'amenities', value: data.amenities },
  ], { key: 'key' }),
  upsert('pool_sessions', data.poolSessions, { sorted: true }),
  upsert('exclusive_packages', data.exclusivePackages, { sorted: true }),
  upsert('units', data.units, { sorted: true }),
  upsert('promos', data.promos),
  upsert('event_packages', data.eventPackages, { sorted: true }),
  upsert('saved_replies', data.savedReplies, { sorted: true }),
].join('\n');

writeFileSync('supabase/seed.sql', sql);
console.log('Wrote supabase/seed.sql');
